"""
=============================================================================================================================================
Problem 2: Even Fibonacci numbers
---------------------------------------------------------------------------------------------------------------------------------------------

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

=============================================================================================================================================
"""


def even_fibonacci():
    fibonacci = [0,1]
    even = []
    current = fibonacci[-1] + fibonacci[-2]

    while current <= 4000000:
        current = fibonacci[-1] + fibonacci[-2]
        fibonacci.append(current)
        if current % 2 == 0: even.append(current)

    return sum(even)

print(even_fibonacci())
